spring:
  output.ansi.enabled: ALWAYS
  jpa:
    hibernate.ddl-auto: 'create-drop'
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/id_banking_db?useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: idBankingUser
    password: 12345
    initialization-mode: ALWAYS
    validationQuery: SELECT 1

users.api: http://localhost:8081/appUsersWS/api/users/
